version: 2

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "16:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  registries:
  - python-index-pypi-python-org-simple
