name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install Black
        run: pip install black

      - name: Run black --check .
        run: black --line-length 120 --check --diff .

      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black --line-length 120 .
          git config --global user.name 'autoblack'
          git config --global user.email 'ekeih@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "fixup: Format Python code with Black"
          git push
