name: "Native Build & Test"

on:
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]
        poetry-version: [ 1.2.2 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install
        run: poetry install

      - id: files
        name: Changed Files Exporter
        uses: futuratrepadeira/changed-files@v4.2.0
        with:
          repo-token: ${{ github.token }}
          pattern: '^.*\.py$'

      - name: Check type hints
        run: |
          if [ -n "${{ steps.files.outputs.files_created }}" ] || [ -n "${{ steps.files.outputs.files_updated }}" ]
          then
            poetry run mypy --show-error-context --show-column-numbers --show-error-codes --pretty ${{ steps.files.outputs.files_created }} ${{ steps.files.outputs.files_updated }}
          fi

      - name: Test with pytest
        run: |
          poetry run pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
